<?php
/**
 * MH User Activity Monitor
 *
 * @package MHUAM
 * @license GPL-2.0-or-later
 */


namespace MHUAM;

if (!defined('ABSPATH')) { exit; }

final class DB {
    public const DB_VERSION_OPTION = 'mhuam_db_version';
    public const DB_VERSION = '1.53';
    private const STATS_CACHE_KEY = 'mhuam_stats_cache';
    private Settings $settings;

    public function __construct(Settings $settings) { $this->settings = $settings; }

    public static function table(): string {
        global $wpdb;
        return $wpdb->prefix . 'mhuam_sessions';
    }


    /**
     * Returns a quoted SQL identifier for plugin-controlled table and column names.
     *
     * WordPress placeholders such as %s must not be used for SQL identifiers like
     * table names, column names or ORDER BY columns. This helper is only used with
     * identifiers generated by the plugin itself or with values already restricted
     * by valid_columns(). It strips every character except ASCII letters, numbers
     * and underscores, then wraps the result in backticks.
     *
     * Do not pass visitor input, request data or unsanitized option values here.
     */
    private static function sql_identifier(string $identifier): string {
        return '`' . preg_replace('/[^A-Za-z0-9_]/', '', $identifier) . '`';
    }

    private static function table_sql(?string $table = null): string {
        return self::sql_identifier($table ?: self::table());
    }

    private static function column_sql(array $columns): string {
        $allowed = self::valid_columns();
        $out = [];
        foreach ($columns as $column) {
            if (in_array($column, $allowed, true)) {
                $out[] = self::sql_identifier($column);
            }
        }
        return implode(', ', $out);
    }

    private static function valid_columns(): array {
        return [
            'session_id','user_id','display_name','user_login','roles','visitor_type','ip_address','ip_display','ip_hash',
            'current_url','page_type','attack_flags_json','page_history_json','referrer','user_agent','is_bot','bot_name',
            'bot_category','bot_risk','cart_json','cart_count','first_seen','last_seen','last_seen_ts','hits','last_ping_source'
        ];
    }

    public static function create_table(): void {
        global $wpdb;
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        $charset = $wpdb->get_charset_collate();
        $table = self::table();
        $sql = "CREATE TABLE {$table} (
            session_id varchar(64) NOT NULL,
            user_id bigint(20) unsigned NOT NULL DEFAULT 0,
            display_name varchar(191) NOT NULL DEFAULT '',
            user_login varchar(80) NOT NULL DEFAULT '',
            roles text NULL,
            visitor_type varchar(60) NOT NULL DEFAULT '',
            ip_address varchar(45) NOT NULL DEFAULT '',
            ip_display varchar(80) NOT NULL DEFAULT '',
            ip_hash char(64) NOT NULL DEFAULT '',
            current_url text NULL,
            page_type varchar(120) NOT NULL DEFAULT '',
            attack_flags_json longtext NULL,
            page_history_json longtext NULL,
            referrer text NULL,
            user_agent text NULL,
            is_bot tinyint(1) NOT NULL DEFAULT 0,
            bot_name varchar(120) NOT NULL DEFAULT '',
            bot_category varchar(80) NOT NULL DEFAULT '',
            bot_risk varchar(20) NOT NULL DEFAULT 'green',
            cart_json longtext NULL,
            cart_count tinyint unsigned NOT NULL DEFAULT 0,
            first_seen datetime NOT NULL,
            last_seen datetime NOT NULL,
            last_seen_ts int(10) unsigned NOT NULL DEFAULT 0,
            hits int(10) unsigned NOT NULL DEFAULT 1,
            last_ping_source varchar(20) NOT NULL DEFAULT '',
            PRIMARY KEY  (session_id),
            KEY last_seen_ts (last_seen_ts),
            KEY last_seen_bot (last_seen_ts, is_bot),
            KEY last_seen_cart (last_seen_ts, cart_count),
            KEY bot_last_seen (is_bot, last_seen_ts),
            KEY risk_last_seen (bot_risk, last_seen_ts),
            KEY type_last_seen (visitor_type, last_seen_ts),
            KEY ip_hash (ip_hash),
            KEY user_id (user_id),
            KEY is_bot (is_bot),
            KEY bot_risk (bot_risk),
            KEY page_type (page_type)
        ) {$charset};";
        dbDelta($sql);
    }

    public static function maybe_upgrade(): void {
        if (get_option(self::DB_VERSION_OPTION) === self::DB_VERSION) {
            return;
        }

        $lock_key = 'mhuam_db_upgrade_lock';
        $lock_time = time();
        $lock_acquired = add_option($lock_key, (string)$lock_time, '', false);
        if (!$lock_acquired) {
            $existing_lock = (int)get_option($lock_key, 0);
            if ($existing_lock > 0 && ($lock_time - $existing_lock) > 10 * MINUTE_IN_SECONDS) {
                delete_option($lock_key);
                $lock_acquired = add_option($lock_key, (string)$lock_time, '', false);
            }
        }
        if (!$lock_acquired) {
            return;
        }

        try {
            self::create_table();
            self::migrate_from_legacy_tables();
            update_option(self::DB_VERSION_OPTION, self::DB_VERSION, false);
        } finally {
            delete_option($lock_key);
        }
    }

    private static function migrate_from_legacy_tables(): void {
        // Legacy table auto-migration intentionally disabled for WordPress.org review compliance.
        // Older session rows are temporary runtime data and can safely expire instead of being
        // copied with dynamically assembled INSERT ... SELECT statements.
        return;
    }

    private static function column_formats(): array {
        return [
            'session_id' => '%s',
            'user_id' => '%d',
            'display_name' => '%s',
            'user_login' => '%s',
            'roles' => '%s',
            'visitor_type' => '%s',
            'ip_address' => '%s',
            'ip_display' => '%s',
            'ip_hash' => '%s',
            'current_url' => '%s',
            'page_type' => '%s',
            'attack_flags_json' => '%s',
            'page_history_json' => '%s',
            'referrer' => '%s',
            'user_agent' => '%s',
            'is_bot' => '%d',
            'bot_name' => '%s',
            'bot_category' => '%s',
            'bot_risk' => '%s',
            'cart_json' => '%s',
            'cart_count' => '%d',
            'first_seen' => '%s',
            'last_seen' => '%s',
            'last_seen_ts' => '%d',
            'hits' => '%d',
            'last_ping_source' => '%s',
        ];
    }

    public function upsert(array $row): void {
        global $wpdb;

        $table = self::table();
        $formats = self::column_formats();
        $data = [];
        $data_formats = [];

        foreach (self::valid_columns() as $column) {
            $data[$column] = $row[$column] ?? '';
            $data_formats[] = $formats[$column];
        }

        $session_id = (string) $data['session_id'];
        if ($session_id === '') {
            return;
        }

        // Use the wpdb helper instead of a custom INSERT ... ON DUPLICATE KEY UPDATE statement.
        // The primary key is session_id, so replace() updates the current runtime row without
        // exposing visitor values to hand-built SQL. The hit counter and first_seen value are
        // supplied by Tracker from short-lived transients.
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime visitor session row is written to the plugin table.
        $result = $wpdb->replace($table, $data, $data_formats);

        self::log_db_error('replace_session', $result);
        if ($result !== false) {
            $this->clear_stats_cache();
        }
        // Synchronous random cleanup was intentionally removed. Cleanup and max-session enforcement are handled by WP-Cron.
    }

    public function get_session(string $session_id): ?array {
        global $wpdb;
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime session lookup is intentionally stored in the plugin table.
        $row = $wpdb->get_row($wpdb->prepare('SELECT * FROM %i WHERE session_id = %s', self::table(), $session_id), ARRAY_A);
        return is_array($row) ? $row : null;
    }

    public function get_sessions(string $filter = 'all', string $orderby = 'last_seen_ts', string $order = 'DESC', int $limit = 250, int $offset = 0): array {
        global $wpdb;
        $allowed = ['last_seen_ts','visitor_type','display_name','ip_display','page_type','hits','is_bot','bot_risk','cart_count'];
        $orderby = in_array($orderby, $allowed, true) ? $orderby : 'last_seen_ts';
        $order = strtoupper($order) === 'ASC' ? 'ASC' : 'DESC';
        $limit = max(1, min(1000, $limit));
        $offset = max(0, $offset);

        if ($filter === 'bots') {
            if ($order === 'ASC') {
                // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime visitor table is intentionally queried for the admin live view.
                $rows = $wpdb->get_results($wpdb->prepare('SELECT * FROM %i WHERE is_bot = %d ORDER BY %i ASC LIMIT %d OFFSET %d', self::table(), 1, $orderby, $limit, $offset), ARRAY_A);
            } else {
                // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime visitor table is intentionally queried for the admin live view.
                $rows = $wpdb->get_results($wpdb->prepare('SELECT * FROM %i WHERE is_bot = %d ORDER BY %i DESC LIMIT %d OFFSET %d', self::table(), 1, $orderby, $limit, $offset), ARRAY_A);
            }
        } elseif ($filter === 'customers') {
            $customer_like = '%' . $wpdb->esc_like('Kunde') . '%';
            if ($order === 'ASC') {
                // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime visitor table is intentionally queried for the admin live view.
                $rows = $wpdb->get_results($wpdb->prepare('SELECT * FROM %i WHERE visitor_type LIKE %s ORDER BY %i ASC LIMIT %d OFFSET %d', self::table(), $customer_like, $orderby, $limit, $offset), ARRAY_A);
            } else {
                // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime visitor table is intentionally queried for the admin live view.
                $rows = $wpdb->get_results($wpdb->prepare('SELECT * FROM %i WHERE visitor_type LIKE %s ORDER BY %i DESC LIMIT %d OFFSET %d', self::table(), $customer_like, $orderby, $limit, $offset), ARRAY_A);
            }
        } elseif ($filter === 'cart') {
            if ($order === 'ASC') {
                // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime visitor table is intentionally queried for the admin live view.
                $rows = $wpdb->get_results($wpdb->prepare('SELECT * FROM %i WHERE cart_count > %d ORDER BY %i ASC LIMIT %d OFFSET %d', self::table(), 0, $orderby, $limit, $offset), ARRAY_A);
            } else {
                // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime visitor table is intentionally queried for the admin live view.
                $rows = $wpdb->get_results($wpdb->prepare('SELECT * FROM %i WHERE cart_count > %d ORDER BY %i DESC LIMIT %d OFFSET %d', self::table(), 0, $orderby, $limit, $offset), ARRAY_A);
            }
        } else {
            if ($order === 'ASC') {
                // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime visitor table is intentionally queried for the admin live view.
                $rows = $wpdb->get_results($wpdb->prepare('SELECT * FROM %i WHERE %d = %d ORDER BY %i ASC LIMIT %d OFFSET %d', self::table(), 1, 1, $orderby, $limit, $offset), ARRAY_A);
            } else {
                // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime visitor table is intentionally queried for the admin live view.
                $rows = $wpdb->get_results($wpdb->prepare('SELECT * FROM %i WHERE %d = %d ORDER BY %i DESC LIMIT %d OFFSET %d', self::table(), 1, 1, $orderby, $limit, $offset), ARRAY_A);
            }
        }

        return is_array($rows) ? $rows : [];
    }

    public function count_sessions(string $filter = 'all'): int {
        global $wpdb;
        if ($filter === 'bots') {
            // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Count is used for admin pagination and contains no visitor-controlled SQL identifiers.
            return (int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM %i WHERE is_bot = %d', self::table(), 1));
        }

        if ($filter === 'customers') {
            // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Count is used for admin pagination and contains no visitor-controlled SQL identifiers.
            return (int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM %i WHERE visitor_type LIKE %s', self::table(), '%' . $wpdb->esc_like('Kunde') . '%'));
        }

        if ($filter === 'cart') {
            // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Count is used for admin pagination and contains no visitor-controlled SQL identifiers.
            return (int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM %i WHERE cart_count > %d', self::table(), 0));
        }

        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Count is used for admin pagination and contains no visitor-controlled SQL identifiers.
        return (int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM %i WHERE %d = %d', self::table(), 1, 1));
    }

    public function get_stats(bool $force_refresh = false): array {
        if (!$force_refresh) {
            $cached = get_transient(self::STATS_CACHE_KEY);
            if (is_array($cached)) {
                return $cached;
            }
        }

        global $wpdb;
        $s = $this->settings->get();
        $online_from = time() - (int)$s['online_seconds'];
        $customer_like = '%' . $wpdb->esc_like('Kunde') . '%';
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Short-lived stats are cached in a transient.
        $row = $wpdb->get_row($wpdb->prepare(
            "SELECT
                COUNT(*) AS total,
                SUM(CASE WHEN last_seen_ts >= %d THEN 1 ELSE 0 END) AS online,
                SUM(CASE WHEN last_seen_ts >= %d AND is_bot = 1 THEN 1 ELSE 0 END) AS bots_online,
                SUM(CASE WHEN last_seen_ts >= %d AND visitor_type LIKE %s THEN 1 ELSE 0 END) AS customers_online,
                SUM(CASE WHEN last_seen_ts >= %d AND cart_count > 0 THEN 1 ELSE 0 END) AS carts,
                SUM(CASE WHEN last_seen_ts >= %d AND attack_flags_json IS NOT NULL AND attack_flags_json != '' AND attack_flags_json != '[]' THEN 1 ELSE 0 END) AS attack_flags,
                SUM(CASE WHEN last_seen_ts >= %d AND bot_risk = 'orange' THEN 1 ELSE 0 END) AS orange,
                SUM(CASE WHEN last_seen_ts >= %d AND bot_risk = 'red' THEN 1 ELSE 0 END) AS red
             FROM %i",
            $online_from, $online_from, $online_from, $customer_like, $online_from, $online_from, $online_from, $online_from, self::table()
        ), ARRAY_A);
        $out = [];
        foreach (['total','online','bots_online','customers_online','carts','attack_flags','orange','red'] as $k) { $out[$k] = (int)($row[$k] ?? 0); }
        set_transient(self::STATS_CACHE_KEY, $out, 10);
        return $out;
    }

    public function clear_stats_cache(): void {
        delete_transient(self::STATS_CACHE_KEY);
    }

    public function cleanup(): void {
        global $wpdb;
        $s = $this->settings->get();
        $older = time() - (int)$s['retention_seconds'];
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime session cleanup is performed by WP-Cron.
        $result = $wpdb->query($wpdb->prepare('DELETE FROM %i WHERE last_seen_ts < %d', self::table(), $older));
        self::log_db_error('cleanup_sessions', $result);
        if ($result !== false && $result > 0) {
            $this->clear_stats_cache();
        }
    }

    public function enforce_max_sessions(): void {
        global $wpdb;
        $max = max(25, (int)$this->settings->get()['max_sessions']);

        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime session count is used only for WP-Cron cleanup.
        $total = (int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM %i WHERE %d = %d', self::table(), 1, 1));
        if ($total <= $max) {
            return;
        }

        $offset = max(0, $max);
        // Select only the old primary keys, then delete them with wpdb::delete() to avoid a hand-built DELETE ... NOT IN statement.
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Runtime session cleanup is performed by WP-Cron.
        $session_ids = $wpdb->get_col($wpdb->prepare('SELECT session_id FROM %i ORDER BY last_seen_ts DESC, session_id DESC LIMIT 18446744073709551615 OFFSET %d', self::table(), $offset));
        if (!is_array($session_ids) || empty($session_ids)) {
            return;
        }

        $deleted = 0;
        foreach ($session_ids as $session_id) {
            // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Deleting expired runtime session rows by primary key.
            $result = $wpdb->delete(self::table(), ['session_id' => (string)$session_id], ['%s']);
            self::log_db_error('enforce_max_sessions_delete_one', $result);
            if ($result !== false) {
                $deleted += (int)$result;
            }
        }

        if ($deleted > 0) {
            $this->clear_stats_cache();
        }
    }


    /**
     * Remove previously stored WooCommerce cart details when the administrator
     * switches to a more data-saving cart mode. This intentionally removes
     * historical cart JSON for existing sessions instead of trying to preserve
     * product names, SKUs or line totals. New sessions will be stored according
     * to the current cart mode.
     */
    public static function clear_stored_cart_details(): void {
        global $wpdb;
        $cart_json = wp_json_encode(['empty' => true]);
        if ($cart_json === false) {
            $cart_json = '{"empty":true}';
        }
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Reduces already stored runtime cart data after a privacy-related setting change.
        $result = $wpdb->query($wpdb->prepare('UPDATE %i SET cart_json = %s, cart_count = %d WHERE %d = %d', self::table(), $cart_json, 0, 1, 1));
        self::log_db_error('clear_stored_cart_details', $result);
        delete_transient(self::STATS_CACHE_KEY);
    }


    /**
     * Remove data that is no longer appropriate after switching to a more
     * restrictive privacy mode. This keeps existing sessions aligned with the
     * current privacy choice instead of waiting for normal retention cleanup.
     */
    public static function reduce_stored_data_for_privacy_mode(string $mode): void {
        if (!in_array($mode, ['data_saving','strict'], true)) {
            return;
        }

        global $wpdb;
        $cart_json = wp_json_encode(['empty' => true]);
        if ($cart_json === false) {
            $cart_json = '{"empty":true}';
        }

        if ($mode === 'strict') {
            // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Reduces already stored runtime data after switching to strict privacy mode.
            $result = $wpdb->query($wpdb->prepare(
                'UPDATE %i SET ip_address = %s, referrer = %s, user_agent = %s, cart_json = %s, cart_count = %d WHERE %d = %d',
                self::table(),
                '',
                '',
                '',
                $cart_json,
                0,
                1,
                1
            ));
            self::log_db_error('reduce_stored_data_for_privacy_mode_strict', $result);
            delete_transient(self::STATS_CACHE_KEY);
            return;
        }

        // Data-saving mode keeps technical session data but removes raw IPs,
        // user agents and product-level cart details from existing rows.
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Reduces already stored runtime data after switching to data-saving privacy mode.
        $result = $wpdb->query($wpdb->prepare(
            'UPDATE %i SET ip_address = %s, user_agent = %s, cart_json = %s, cart_count = CASE WHEN cart_count > 0 THEN cart_count ELSE %d END WHERE user_agent != %s OR ip_address != %s OR cart_json LIKE %s',
            self::table(),
            '',
            '',
            $cart_json,
            0,
            '',
            '',
            '%' . $wpdb->esc_like('"items"') . '%'
        ));
        self::log_db_error('reduce_stored_data_for_privacy_mode_data_saving', $result);
        delete_transient(self::STATS_CACHE_KEY);
    }

    public function clear(): void {
        global $wpdb;
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Administrator-requested clear action for runtime session rows.
        $result = $wpdb->query($wpdb->prepare('DELETE FROM %i WHERE %d = %d', self::table(), 1, 1));
        self::log_db_error('clear_sessions', $result);
        if ($result !== false) {
            $this->clear_stats_cache();
        }
    }

    public static function log_db_error(string $operation, $result): void {
        global $wpdb;
        if ($result !== false || empty($wpdb->last_error)) {
            return;
        }

        $message = sprintf(
            '[MH User Activity Monitor] Database write failed during %s: %s',
            sanitize_key($operation),
            wp_strip_all_tags((string)$wpdb->last_error)
        );

        set_transient('mhuam_last_db_error', $message, HOUR_IN_SECONDS);
        do_action('mhuam_database_error', $message, $operation, $wpdb->last_error);
    }

}
